### ISSUE TITLE
Pregunta

### ISSUE THREAD

**Issue by edgarmlz** [rvf0068/programacion-lineal-2020#1]

**Comment by edgarmlz** [comment]
La mayonesa es un instrumento?

**Comment by aliciaalice8** [comment]
no, Patricio, la mayonesa no es un instrumento

**Comment by edgarmlz** [comment]
> 1011121314

**Comment by aliciaalice8** [comment]
![imagen](https://user-images.githubusercontent.com/60108842/76978115-e5d14a80-68fb-11ea-9bbf-69ad59ba8158.png)

**Comment by Nesbaid** [comment]
![cmcwCJ-G_400x400](https://user-images.githubusercontent.com/60108733/76977996-c0444100-68fb-11ea-85b3-f167f12dcf3b.jpg)
