### ISSUE TITLE
Pregunta seria

### ISSUE THREAD

**Issue by MarianaChavez6686** [rvf0068/programacion-lineal-2020#12]
¿De dónde vienen los bebés?

**Comment by edgarmlz** [comment]
pues mi mamá me dijo que me encontraron en la basura :v

**Comment by aliciaalice8** [comment]
ja ja

**Comment by aliciaalice8** [comment]
8000044800 
www.gob.mx/coronavirus

**Comment by aliciaalice8** [comment]
Los trae la cigueña, desde Paris (pero alli hay coronavirus), por eso el link y el numero
