### ISSUE TITLE
pregunta problema 2

### ISSUE THREAD

**Issue by AnaPerla25** [rvf0068/programacion-lineal-2020#28]
doctor buenos días
la región factible es no acotada en el problema 2, con lo cual el problema cambia a encontrar el punto donde se alcanza el valor mínimo  
esto es correcto?

**Comment by rvf0068** [comment]
No, en este caso tienes que dar una demostración de que la región no es acotada. El método simplex
puede ayudar en eso, pues te da una variable cuyo crecimiento no está restringido. De este modo puedes demostrar que hay puntos en la región factible donde la función objetivo se hace arbitrariamente grande.
