### ISSUE TITLE
Fase 1

### ISSUE THREAD

**Issue by edgarmlz** [rvf0068/programacion-lineal-2020#29]
Usando la fase 1, como nos dábamos cuenta que el problema no tenia solución?

**Comment by MarianaChavez6686** [comment]
Es cuándo en el tablero simplex las variables de corrección no se hacen cero y ya no puedes seguir aumentandolas?

**Comment by rvf0068** [comment]
Así es, si en la fase 1 las variables de corrección no se pueden hacer cero, se deduce que la región factible es vacía, y por lo tanto, el problema original no tiene solución.
