### ISSUE TITLE
duda ejercicio 1.

### ISSUE THREAD

**Issue by DianaSB21** [rvf0068/programacion-lineal-2020#30]
Profesor @rvf0068  buenas tardes.
tengo duda en como resolver el ejercicio ya que la función objetivo tiene dos variables y las restricciones tienen tres variables.

**Comment by rvf0068** [comment]
No es una complicación especial que no todas las variables aparezcan. Si recuerdas, por ejemplo, en cualquier problema donde se añaden variables de holgura, esas variables no están tampoco en la función objetivo.

**Comment by DianaSB21** [comment]
gracias
