### ISSUE TITLE
Problema 2, fase 1

### ISSUE THREAD

**Issue by AnaPerla25** [rvf0068/programacion-lineal-2020#31]
Buen doctor, podría recordarme en qué momento es que se recurre a la fase 1  y cómo es que se realiza el primer paso

**Comment by rvf0068** [comment]
Conviene hacer la fase 1 cuando no está claro cómo obtener un tablero inicial.

Antes de la suspensión, vimos unos ejemplos en los cuales logramos un tablero inicial válido intentando varias elecciones de variables básicas, hasta encontrar un tablero dado. Si eso se logra, entonces no es necesario usar la fase 1.

Sin embargo, hay ocasiones donde quizás hay muchas variables, y en ese caso puede ser más rápido usar la fase 1, para encontrar un tablero inicial que sea válido.
