### ISSUE TITLE
Pregunta del video 

### ISSUE THREAD

**Issue by AnaPerla25** [rvf0068/programacion-lineal-2020#32]
Doctor buena tarde...
El método de las matrices me pareció en lo más práctico, pero me quedo la duda de por ejemplo, como deberíamos darnos cuenta en cuestión de las matrices que el problema requiere emplear la fase 1...Espero darme a entender

De antemano gracias

**Comment by rvf0068** [comment]
Hola
Esa parte no tiene diferencia, lo que importa es si puedes encontrar variables que sean básicas en un tablero inicial válido. Si las puedes encontrar, no es necesaria la fase 1. 

Por otro lado, por supuesto que se puede usar las matrices para aplicar la fase 1, pues en ese caso las variables de corrección siempre se pueden hacer funcionar como variables básicas de un tablero inicial válido.
