### ISSUE TITLE
Pregunta antigua 

### ISSUE THREAD

**Issue by AnaPerla25** [rvf0068/programacion-lineal-2020#33]
Dr. Buena tarde...
Disculpe por volver a preguntar de un ejercicio visto en clase hace tiempo, estaba resolviendo de nuevo el primer ejercicio de la lista del 2 de marzo... Yo lo intente aumentando una variable pero en las restricciones no es claro ver cual restringe mas el crecimiento, pues alguna me salen números negativos .
Cheque su solución y no noto como es que despejó, me haría favor de poder recordarme 

De antemano gracias.

**Comment by rvf0068** [comment]
Sería bueno que pusieras más detalles del problema, pues no recuerdo cual es la solución mía a la que te refieres. Lo poco que recuerdo es que ese ejemplo muestra que no siempre es claro escoger un tablero inicial válido. Es decir, habría que usar la fase 1 o bien, escoger juiciosamente las variables básicas de modo que quede un tablero válido.

Sin embargo, recuerda que al escoger la variable que restringe más el crecimiento, la idea es seguir conservando un tablero válido, es decir, que todas las variables sigan siendo mayores o iguales a cero. Si el aumentar una variable no básica en una ecuación no cambia el signo de la variable básica, entonces esa ecuación no restringe el crecimiento de la variable no básica, y no se considera.

**Comment by AnaPerla25** [comment]
Doctor que está sucediendo en este ejercicio?

**Comment by rvf0068** [comment]
No entiendo tu pregunta, ¿podrías por favor detallarla?
