### ISSUE TITLE
Problema 2, lista 2704

### ISSUE THREAD

**Issue by AnaPerla25** [rvf0068/programacion-lineal-2020#34]
Doctor buena tarde, en el ejercicio 2 estoy ocupando el método de coeficientes, al escribir la primer matriz decido aumentar la variable x1 y al realizar las operaciones inmediato me queda en el último renglón puros coeficientes positivos pero aún no puedo saber cuál es el valor máximo y en donde se alcanza...
Que necesito hacer?

**Comment by rvf0068** [comment]
En cada problema, antes de iniciar debes de saber cuáles son las variables básicas. En el ejercicio que mencionas, no se ve claro a priori cuáles serían, por lo que debe aplicarse la Fase 1.
